/*
 zKølang by NØNOS
 AGPL-3.0-or-later
*/

use super::tables::{perm, tables};
use nonos_stark::air::{Poseidon, NOTE_DOMAIN, RATE, WIDTH};
use std::fmt::Write as _;

pub(super) fn render(h: &Poseidon, rounds: usize) -> String {
    let mut s = String::new();
    writeln!(
        s,
        "// Poseidon-Goldilocks note commitment, width {WIDTH}, {rounds} full rounds."
    )
    .unwrap();
    writeln!(
        s,
        "// The hash ShieldedPool deploys, so a commitment here is the one deposit"
    )
    .unwrap();
    writeln!(
        s,
        "// computes on chain. Generated by note_commit_gen; do not edit the tables."
    )
    .unwrap();
    writeln!(s, "fn s7(x) = x * x * x * x * x * x * x;").unwrap();
    tables(h, rounds, &mut s);
    writeln!(s).unwrap();
    for l in 0..11 {
        writeln!(s, "witness l{l};").unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "let state = [l0, l1, l2, l3, l4, l5, l6, l7];").unwrap();
    perm(rounds, &mut s);
    for k in 0..RATE {
        writeln!(s, "let d0_{k} = state[{k}];").unwrap();
    }
    writeln!(s, "let state = [l8, l9, l10, {NOTE_DOMAIN}, 0, 0, 0, 0];").unwrap();
    perm(rounds, &mut s);
    for k in 0..RATE {
        writeln!(s, "let d1_{k} = state[{k}];").unwrap();
    }
    writeln!(
        s,
        "let state = [d0_0, d0_1, d0_2, d0_3, d1_0, d1_1, d1_2, d1_3];"
    )
    .unwrap();
    perm(rounds, &mut s);
    for k in 0..RATE {
        writeln!(s, "reveal state[{k}];").unwrap();
    }
    s
}
