/*
 zKølang by NØNOS
 AGPL-3.0-or-later
*/

use super::tables::{perm, tables};
use nonos_stark::air::{Poseidon, NOTE_DOMAIN, RATE, WIDTH};
use std::fmt::Write as _;

pub(super) fn render(h: &Poseidon, rounds: usize) -> String {
    let mut s = String::new();
    writeln!(
        s,
        "// Poseidon-Goldilocks note commitment, width {WIDTH}, {rounds} full rounds."
    )
    .unwrap();
    writeln!(
        s,
        "// The hash ShieldedPool deploys, so a commitment here is the one deposit"
    )
    .unwrap();
    writeln!(
        s,
        "// computes on chain. Generated by note_commit_gen; do not edit the tables."
    )
    .unwrap();
    writeln!(s, "fn s7(x) = x * x * x * x * x * x * x;").unwrap();
    tables(h, rounds, &mut s);
    writeln!(s).unwrap();
    for l in 0..11 {
        writeln!(s, "witness l{l};").unwrap();
    }
    writeln!(s).unwrap();
    /* The owner is the spend key and the blinding compressed; the commitment is the
     * public quad, value, asset and the domain, compressed with the owner. */
    writeln!(s, "let state = [l3, l4, l5, l6, l7, l8, l9, l10];").unwrap();
    perm(rounds, &mut s);
    for k in 0..RATE {
        writeln!(s, "let o{k} = state[{k}];").unwrap();
    }
    writeln!(
        s,
        "let state = [l0, l1, l2, {NOTE_DOMAIN}, o0, o1, o2, o3];"
    )
    .unwrap();
    perm(rounds, &mut s);
    for k in 0..RATE {
        writeln!(s, "reveal state[{k}];").unwrap();
    }
    s
}
