/*
 zKølang by NØNOS
 AGPL-3.0-or-later
*/

//! MiMC, a real algebraic hash written in zKolang. The permutation iterates
//! `s = (s + c_i)^7` over the Goldilocks field. The x^7 S-box is a genuine
//! permutation because 7 is coprime to p - 1, so the map is invertible and the
//! round count gives its security. The round constants are a nothing-up-my-sleeve
//! Weyl sequence, fixed here so the emitted program, the generator, and the proof
//! all read the same numbers. This module is the single source of truth: it emits
//! the zKolang source and computes the reference the proof checks against.

use nonos_stark::field::Fp;

/// The number of rounds. Each round is one S-box, so the algebraic degree after r
/// rounds is 7^r, which passes the field size well before the last round.
pub const ROUNDS: usize = 16;

/// The round constants, a Weyl sequence seeded by the golden-ratio constant. Any
/// fixed distinct sequence works; this one is reproducible and free of structure.
pub fn round_constants() -> [u64; ROUNDS] {
    let mut c = [0u64; ROUNDS];
    let mut x = 0x9E37_79B9_7F4A_7C15u64;
    for slot in c.iter_mut() {
        *slot = x;
        x = x.wrapping_mul(0x9E37_79B9_7F4A_7C15).wrapping_add(1);
    }
    c
}

/// Emit the MiMC permutation as a zKolang program: a constant table of the round
/// constants, the x^7 S-box as a function, and the round loop over the table.
pub fn source() -> String {
    let c = round_constants();
    let table: Vec<String> = c.iter().map(|v| format!("{v}")).collect();
    format!(
        "// MiMC permutation over Goldilocks, x^7 S-box, {ROUNDS} rounds.\n\
         // The round constants are a fixed Weyl sequence. Generated by gen_mimc.\n\
         const C = [{table}];\n\
         \n\
         // The x^7 S-box, a permutation of the field.\n\
         fn pow7(x) = x * x * x * x * x * x * x;\n\
         \n\
         input x;\n\
         let s = x;\n\
         for i in 0 .. {ROUNDS} {{\n\
         \x20   let s = pow7(s + C[i]);\n\
         }}\n\
         output s;\n",
        table = table.join(", "),
    )
}

/// The reference value the program must produce: the same rounds in the field.
pub fn reference(input: u64) -> u64 {
    let c = round_constants();
    let mut s = Fp::from_u64(input);
    for ci in c {
        s = (s + Fp::from_u64(ci)).pow(7);
    }
    s.value()
}
