/*
 zKølang by NØNOS
 AGPL-3.0-or-later
*/

//! Regenerates `circuits/shield/note_commit.zkl` from the hash the pool actually
//! deploys.
//!
//! The circuit is a full unroll: one mixing function per round with that round's
//! constant as the constant term, so the round count is baked into the source.
//! Writing those tables by hand is how the circuit ended up on a four round
//! Poseidon while `ShieldedPool` commits under thirty two, which means every note
//! the circuit produced would hash to something `deposit` never computes.
//!
//! So the tables are generated here from `nonos-stark` itself rather than
//! transcribed. The round constants come straight off the public API. The mixing
//! matrix is private, but it can be read back through that same API: the S-box
//! fixes zero and one, so running a round on the i-th unit vector with zero
//! constants returns the matrix's i-th column.
//!
//! Run with `--ignored` after changing the hash, then commit the regenerated
//! circuit. `note_commit_tests` is what proves the result agrees with the
//! deployed digest.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use nonos_stark::air::{Poseidon, NOTE_DOMAIN, RATE, WIDTH};
use nonos_stark::field::Fp;

/// The pool's hash: `1 << 5` rounds, matching `FULL_ROUNDS` in
/// `PoseidonGoldilocks.sol`.
const POOL_LOG_ROUNDS: u32 = 5;

fn circuit_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop();
    p.push("circuits/shield/note_commit.zkl");
    p
}

/// Column `i` of the mixing matrix, read back through the public round function.
fn mds_column(h: &Poseidon, i: usize) -> [Fp; WIDTH] {
    let mut unit = [Fp::ZERO; WIDTH];
    unit[i] = Fp::ONE;
    h.round_with_rc(&unit, &[Fp::ZERO; WIDTH])
}

fn mds(h: &Poseidon) -> [[Fp; WIDTH]; WIDTH] {
    let cols: Vec<[Fp; WIDTH]> = (0..WIDTH).map(|i| mds_column(h, i)).collect();
    let mut m = [[Fp::ZERO; WIDTH]; WIDTH];
    for (j, row) in m.iter_mut().enumerate() {
        for (i, cell) in row.iter_mut().enumerate() {
            *cell = cols[i][j];
        }
    }
    m
}

fn render(h: &Poseidon, rounds: usize) -> String {
    let m = mds(h);
    let mut s = String::new();

    writeln!(
        s,
        "// Poseidon-Goldilocks note commitment, width {WIDTH}, {rounds} full rounds, Cauchy MDS."
    )
    .unwrap();
    writeln!(
        s,
        "// A fixed-arity commitment over eleven field elements: each round runs the x^7"
    )
    .unwrap();
    writeln!(
        s,
        "// S-box on every lane into a mixing layer that adds the round constant. The"
    )
    .unwrap();
    writeln!(
        s,
        "// eleven limbs plus a domain tag compress into one digest."
    )
    .unwrap();
    writeln!(s, "//").unwrap();
    writeln!(
        s,
        "// This is the hash ShieldedPool deploys, so a commitment computed here is the"
    )
    .unwrap();
    writeln!(
        s,
        "// commitment deposit computes on chain. Generated by note_commit_gen; do not"
    )
    .unwrap();
    writeln!(s, "// edit the tables by hand.").unwrap();
    writeln!(
        s,
        "// Run: zkolang run circuits/shield/note_commit.zkl --witness 1,2,3,4,5,6,7,8,9,10,11"
    )
    .unwrap();
    writeln!(s, "fn s7(x) = x * x * x * x * x * x * x;").unwrap();

    for r in 0..rounds {
        let rc = h.round_constant(r);
        writeln!(s, "fn mix{r}(s) = [").unwrap();
        for (j, row) in m.iter().enumerate() {
            let mut line = format!("    {}", rc[j].value());
            for (i, coeff) in row.iter().enumerate() {
                write!(line, " + {} * s[{}]", coeff.value(), i).unwrap();
            }
            if j + 1 < WIDTH {
                line.push(',');
            }
            writeln!(s, "{line}").unwrap();
        }
        writeln!(s, "];").unwrap();
    }

    writeln!(s).unwrap();
    for l in 0..11 {
        writeln!(s, "witness l{l};").unwrap();
    }
    writeln!(s).unwrap();

    // One permutation, written out as the language sees it.
    let perm = |s: &mut String| {
        for r in 0..rounds {
            let lanes: Vec<String> = (0..WIDTH).map(|i| format!("s7(state[{i}])")).collect();
            writeln!(s, "let sb = [{}];", lanes.join(", ")).unwrap();
            writeln!(s, "let state = mix{r}(sb);").unwrap();
        }
    };

    // d0 = compress(limbs[0..4], limbs[4..8])
    writeln!(s, "let state = [l0, l1, l2, l3, l4, l5, l6, l7];").unwrap();
    perm(&mut s);
    for k in 0..RATE {
        writeln!(s, "let d0_{k} = state[{k}];").unwrap();
    }

    // d1 = compress(limbs[8..11] ++ domain, zeros)
    writeln!(s, "let state = [l8, l9, l10, {NOTE_DOMAIN}, 0, 0, 0, 0];").unwrap();
    perm(&mut s);
    for k in 0..RATE {
        writeln!(s, "let d1_{k} = state[{k}];").unwrap();
    }

    // cm = compress(d0, d1)
    writeln!(
        s,
        "let state = [d0_0, d0_1, d0_2, d0_3, d1_0, d1_1, d1_2, d1_3];"
    )
    .unwrap();
    perm(&mut s);
    for k in 0..RATE {
        writeln!(s, "reveal state[{k}];").unwrap();
    }

    s
}

#[test]
#[ignore]
fn regenerate_note_commit_circuit() {
    let h = Poseidon::new(POOL_LOG_ROUNDS, [Fp::ZERO; RATE]);
    let rounds = 1usize << POOL_LOG_ROUNDS;
    let src = render(&h, rounds);
    let path = circuit_path();
    fs::write(&path, src).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
}

/// The generator must describe the hash it claims to. If the round count in the
/// committed circuit drifts from the pool's, the circuit commits notes the pool
/// cannot recognise, so this is checked on every run rather than on demand.
#[test]
fn the_committed_circuit_matches_the_pool_round_count() {
    let src = fs::read_to_string(circuit_path()).expect("read circuit");
    let rounds = 1usize << POOL_LOG_ROUNDS;
    assert!(
        src.contains(&format!("fn mix{}(s)", rounds - 1)),
        "circuit is missing round {}, so it is not the pool's hash",
        rounds - 1
    );
    assert!(
        !src.contains(&format!("fn mix{rounds}(s)")),
        "circuit has more rounds than the pool's hash"
    );
}

/// The generator reconstructs the permutation from the public API. If that
/// reconstruction is wrong, every table it emits is confidently wrong, so it is
/// checked against the hash itself before any circuit is written.
#[test]
fn the_reconstructed_permutation_matches_the_hash() {
    let h = Poseidon::new(POOL_LOG_ROUNDS, [Fp::ZERO; RATE]);
    let rounds = 1usize << POOL_LOG_ROUNDS;
    let m = mds(&h);

    // A round, rebuilt the way the emitted tables compute it.
    let rebuilt = |state: [Fp; WIDTH], r: usize| -> [Fp; WIDTH] {
        let rc = h.round_constant(r);
        let sb: Vec<Fp> = state.iter().map(|v| v.pow(7)).collect();
        let mut out = [Fp::ZERO; WIDTH];
        for j in 0..WIDTH {
            let mut acc = rc[j];
            for i in 0..WIDTH {
                acc = acc + m[j][i] * sb[i];
            }
            out[j] = acc;
        }
        out
    };

    let mut state = [Fp::ZERO; WIDTH];
    for (i, v) in state.iter_mut().enumerate() {
        *v = Fp::from_u64(i as u64 + 1);
    }
    let mut mine = state;
    for r in 0..rounds {
        mine = rebuilt(mine, r);
    }
    let theirs = h.permute(state);
    assert_eq!(
        mine, theirs,
        "reconstructed permutation disagrees with nonos-stark"
    );
}

/// The commitment costs three permutations and compiles to a little under
/// twenty four thousand operations, so a permutation is roughly eight thousand.
///
/// That number is worth keeping in front of anyone who proposes moving a Shield
/// hot path into the language. A depth thirty two membership climb is one
/// permutation per level, so it lands near a quarter of a million operations for
/// a statement the hand written air proves in a two thousand row region. The
/// language earns its place on programs whose shape is not known in advance,
/// which is the proving market; a fixed protocol circuit that runs on every
/// transfer does not benefit from a general machine.
///
/// The bound is here to catch a regression in the compiler or the generator, not
/// to be tuned. If it trips, find out what grew.
#[test]
fn the_commitment_circuit_fits_its_op_budget() {
    let ops = nonos_zkolang::compile_source(&std::fs::read_to_string(circuit_path()).unwrap())
        .expect("compile");
    assert!(
        ops.len() < 30_000,
        "note_commit compiles to {} ops",
        ops.len()
    );
}
