// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! The inner AIR's periodic columns evaluated at the out-of-domain point, in
//! circuit. A recursive composition check consumes `P_j(z)` for each inner
//! periodic column; left as prover inputs those values are forgeable, so this
//! gadget recomputes them from `z` with the barycentric form over the inner
//! trace domain `H`: `P(z) = (z^t - 1)/t * sum_i v_i * h^i / (z - h^i)`. One
//! row per domain point and column: it witnesses the quotient
//! `q_i = v_i h^i / (z - h^i)` against the structural constants `v_i`, `h^i`
//! and accumulates it; a power tower squares `z` up to `z^t`; and each run
//! lands on `P_j(z)` in an output cell the assembly binds to where the
//! composition consumes it. The column values and domain points are periodic
//! constants, `z` is a witness bound to the transcript squeeze, so the AIR
//! carries no instance data.

use super::super::field::{Felt, Fp, Fp2};
use super::spec::{Air, AirExt};
use alloc::vec::Vec;

/// The extension non-residue, so `(p + q X)(r + s X) = (pr + W qs) + (ps + qr) X`.
const W: u64 = 7;

pub struct PeriodicZ {
    log_rows: u32,
    log_t: u32,
    h: Fp,
    cols: Vec<Vec<Fp>>,
    z: Fp2,
}

impl PeriodicZ {
    /// The recompute of `cols` (each of length `2^log_t`, the inner trace
    /// domain generated by `h`) at the witnessed point `z`.
    pub fn new(log_t: u32, h: Fp, cols: Vec<Vec<Fp>>, z: Fp2) -> PeriodicZ {
        let t = 1usize << log_t;
        let log_rows = (cols.len() * t).next_power_of_two().trailing_zeros();
        PeriodicZ { log_rows, log_t, h, cols, z }
    }

    fn t(&self) -> usize {
        1usize << self.log_t
    }

    /// `(z^t - 1) / t`, the barycentric prefactor every run scales by.
    fn prefactor(&self) -> Fp2 {
        let t = self.t() as u64;
        (self.z.pow(t) - Fp2::ONE) * Fp2::from_base(Fp::from_u64(t)).inv()
    }

    fn quotient(&self, j: usize, i: usize) -> Fp2 {
        let x = self.h.pow(i as u64);
        Fp2::from_base(self.cols[j][i] * x) * (self.z - Fp2::from_base(x)).inv()
    }

    /// The derived evaluations, one per column, for the caller to bind against.
    pub fn values(&self) -> Vec<Fp2> {
        let e = self.prefactor();
        (0..self.cols.len())
            .map(|j| {
                let mut acc = Fp2::ZERO;
                for i in 0..self.t() {
                    acc = acc + self.quotient(j, i);
                }
                acc * e
            })
            .collect()
    }

    /// The `(row, column)` of each column's evaluation cell, in column order.
    pub fn value_cells(&self) -> Vec<(usize, usize)> {
        let t = self.t();
        (0..self.cols.len()).map(|j| (j * t + t - 1, 10)).collect()
    }

    /// The witness: the quotient and running sum per row, the constant `z` and
    /// prefactor, the power tower in the first rows, each run's evaluation on
    /// its last row.
    pub fn trace(&self) -> Vec<Fp> {
        let rows = 1usize << self.log_rows;
        let w = self.trace_width();
        let e = self.prefactor();
        let mut tr = alloc::vec![Fp::ZERO; rows * w];
        for r in 0..rows {
            tr[r * w + 4] = self.z.c0;
            tr[r * w + 5] = self.z.c1;
            tr[r * w + 8] = e.c0;
            tr[r * w + 9] = e.c1;
        }
        let mut tw = self.z;
        for k in 0..=self.log_t as usize {
            tr[k * w + 6] = tw.c0;
            tr[k * w + 7] = tw.c1;
            tw = tw.square();
        }
        for j in 0..self.cols.len() {
            let mut acc = Fp2::ZERO;
            for i in 0..self.t() {
                let r = j * self.t() + i;
                let q = self.quotient(j, i);
                tr[r * w] = q.c0;
                tr[r * w + 1] = q.c1;
                tr[r * w + 2] = acc.c0;
                tr[r * w + 3] = acc.c1;
                acc = acc + q;
            }
            let out = acc * e;
            let r = j * self.t() + self.t() - 1;
            tr[r * w + 10] = out.c0;
            tr[r * w + 11] = out.c1;
        }
        tr
    }

    fn transition_impl<F: Felt>(&self, window: &[F], periodic: &[F]) -> Vec<F> {
        let stride = self.trace_width();
        let rd = |slot: usize| -> (F, F) { (window[2 * slot], window[2 * slot + 1]) };
        let rdn =
            |slot: usize| -> (F, F) { (window[stride + 2 * slot], window[stride + 2 * slot + 1]) };
        let w = F::from_base(Fp::from_u64(W));
        let mul =
            |a: (F, F), b: (F, F)| -> (F, F) { (a.0 * b.0 + w * a.1 * b.1, a.0 * b.1 + a.1 * b.0) };

        let (q, acc, z, tw, e, out) = (rd(0), rd(1), rd(2), rd(3), rd(4), rd(5));
        let (nacc, nz, ntw, ne) = (rdn(1), rdn(2), rdn(3), rdn(4));
        let x = periodic[0];
        let v = periodic[1];
        let sel = periodic[2];
        let rb = periodic[3];
        let sel0 = periodic[4];
        let twsel = periodic[5];
        let esel = periodic[6];
        let tval = F::from_base(Fp::from_u64(self.t() as u64));
        let one = F::ONE;

        // q * (z - h^i) = v * h^i, on the term rows.
        let d = (z.0 - x, z.1);
        let qd = mul(q, d);
        // The sum accumulates each term and resets at a run boundary.
        let step = (acc.0 + sel * q.0, acc.1 + sel * q.1);
        // The tower squares z up to z^t; the prefactor cell is (z^t - 1)/t.
        let tw2 = mul(tw, tw);
        // Each run's output cell is the accumulated sum times the prefactor.
        let total = (acc.0 + q.0, acc.1 + q.1);
        let scaled = mul(total, e);

        alloc::vec![
            sel * (qd.0 - v * x),
            sel * qd.1,
            nacc.0 - (one - rb) * step.0,
            nacc.1 - (one - rb) * step.1,
            nz.0 - z.0,
            nz.1 - z.1,
            ne.0 - e.0,
            ne.1 - e.1,
            twsel * (ntw.0 - tw2.0),
            twsel * (ntw.1 - tw2.1),
            sel0 * (tw.0 - z.0),
            sel0 * (tw.1 - z.1),
            esel * (e.0 * tval - tw.0 + one),
            esel * (e.1 * tval - tw.1),
            rb * (out.0 - scaled.0),
            rb * (out.1 - scaled.1),
        ]
    }
}

impl AirExt for PeriodicZ {
    fn transition_ext(&self, window: &[Fp2], periodic: &[Fp2]) -> Vec<Fp2> {
        self.transition_impl(window, periodic)
    }
}

impl Air for PeriodicZ {
    fn log_trace_len(&self) -> u32 {
        self.log_rows
    }

    fn trace_width(&self) -> usize {
        12
    }

    fn window_size(&self) -> usize {
        2
    }

    fn constraint_degree(&self) -> usize {
        // A selector times the quotient times the point, and the run boundary
        // times the sum times the prefactor: three factors.
        3
    }

    fn num_transition(&self) -> usize {
        16
    }

    fn periodic_columns(&self) -> Vec<Vec<Fp>> {
        let rows = 1usize << self.log_rows;
        let t = self.t();
        let active = self.cols.len() * t;
        let mut x = Vec::with_capacity(rows);
        let mut v = Vec::with_capacity(rows);
        let mut sel = Vec::with_capacity(rows);
        let mut rb = Vec::with_capacity(rows);
        let mut sel0 = Vec::with_capacity(rows);
        let mut twsel = Vec::with_capacity(rows);
        let mut esel = Vec::with_capacity(rows);
        for r in 0..rows {
            let i = r % t;
            x.push(self.h.pow(i as u64));
            v.push(if r < active { self.cols[r / t][i] } else { Fp::ZERO });
            sel.push(if r < active { Fp::ONE } else { Fp::ZERO });
            rb.push(if r < active && i == t - 1 { Fp::ONE } else { Fp::ZERO });
            sel0.push(if r == 0 { Fp::ONE } else { Fp::ZERO });
            twsel.push(if r < self.log_t as usize { Fp::ONE } else { Fp::ZERO });
            esel.push(if r == self.log_t as usize { Fp::ONE } else { Fp::ZERO });
        }
        alloc::vec![x, v, sel, rb, sel0, twsel, esel]
    }

    fn transition(&self, window: &[Fp], periodic: &[Fp]) -> Vec<Fp> {
        self.transition_impl(window, periodic)
    }

    fn boundary(&self) -> Vec<(usize, usize, Fp)> {
        // Only the structural sum start: everything else is witness, bound by
        // the assembly.
        alloc::vec![(2, 0, Fp::ZERO), (3, 0, Fp::ZERO)]
    }
}
