// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! A Poseidon hash over the Goldilocks field, and the AIR that proves knowledge
//! of a preimage. The permutation has real parameters, not a demonstration:
//!
//!  - width 8, a rate of 4 and a capacity of 4 (a 256-bit capacity, so the
//!    sponge targets 128-bit security),
//!  - the x^7 S-box, which is a permutation of this field because 7 is coprime
//!    to the group order,
//!  - a maximum-distance-separable diffusion matrix built as a Cauchy matrix,
//!    which is provably MDS for any distinct node sets,
//!  - a full S-box layer every round (no partial rounds), so the round function
//!    is uniform and every lane is fully mixed each round,
//!  - round constants generated by a nothing-up-my-sleeve rule, the BLAKE3 hash
//!    of a domain string with the round and lane indices, so they are
//!    reproducible and free of hidden structure.
//!
//! The capacity lane group is initialized to zero at the first row, the sponge
//! domain separation. The proof shows a public digest, the rate lanes at the
//! final row, is the hash of some input the proof never reveals: knowledge of a
//! preimage.

use super::super::field::{Felt, Fp, Fp2};
use super::spec::{Air, AirExt};
use crate::hash::blake3_hash;
use alloc::vec::Vec;

/// State width in field elements.
pub const WIDTH: usize = 8;
/// Rate: the number of lanes that absorb input and emit the digest.
pub const RATE: usize = 4;

/// The fixed arity of the field commitment: eleven field elements in one digest.
pub const NOTE_LIMBS: usize = 11;

/// Domain tag placed in the commitment preimage, ASCII "NOTE". It separates a
/// field commitment from a bare two-to-one tree node, both of which use the same
/// compression, so a commitment can never be confused with an internal node.
pub const NOTE_DOMAIN: u64 = 0x4E4F_5445;

const RC_DOMAIN: &[u8] = b"NONOS-POSEIDON-GOLDILOCKS-RC";

#[derive(Clone)]
pub struct Poseidon {
    log_t: u32,
    mds: [[Fp; WIDTH]; WIDTH],
    rc: Vec<[Fp; WIDTH]>,
    digest: [Fp; RATE],
}

impl Poseidon {
    /// Build the hash and its preimage AIR for `2^log_t` rounds and a public
    /// `digest`.
    pub fn new(log_t: u32, digest: [Fp; RATE]) -> Poseidon {
        let rounds = 1usize << log_t;
        Poseidon { log_t, mds: cauchy_mds(), rc: round_constants(rounds), digest }
    }

    /// One round of the permutation on a full state: full x^7 S-box layer, then
    /// the MDS mix, then the round constants. Used by the prover to build the
    /// trace and by callers to compute a digest.
    pub fn round(&self, state: &[Fp; WIDTH], round: usize) -> [Fp; WIDTH] {
        let mut sbox = [Fp::ZERO; WIDTH];
        for (s, v) in sbox.iter_mut().zip(state.iter()) {
            *s = (*v).pow(7);
        }
        let mut out = [Fp::ZERO; WIDTH];
        for (j, o) in out.iter_mut().enumerate() {
            let mut acc = self.rc[round][j];
            for (m, s) in self.mds[j].iter().zip(sbox.iter()) {
                acc = acc + *m * *s;
            }
            *o = acc;
        }
        out
    }

    /// Hash a rate-sized input: seed the capacity with zero, run every round but
    /// the last, and read the digest from the final rate lanes.
    pub fn hash(&self, input: &[Fp; RATE]) -> [Fp; RATE] {
        let mut state = [Fp::ZERO; WIDTH];
        state[..RATE].copy_from_slice(input);
        let rounds = 1usize << self.log_t;
        for r in 0..rounds - 1 {
            state = self.round(&state, r);
        }
        let mut digest = [Fp::ZERO; RATE];
        digest.copy_from_slice(&state[..RATE]);
        digest
    }

    /// One round using externally supplied constants: full x^7 S-box, MDS mix,
    /// then add `rc`. The membership AIR feeds the round constants as periodic
    /// values, so it shares this exact round function with the hash.
    pub fn round_with_rc(&self, state: &[Fp; WIDTH], rc: &[Fp; WIDTH]) -> [Fp; WIDTH] {
        let mut sbox = [Fp::ZERO; WIDTH];
        for (s, v) in sbox.iter_mut().zip(state.iter()) {
            *s = (*v).pow(7);
        }
        let mut out = [Fp::ZERO; WIDTH];
        for (j, o) in out.iter_mut().enumerate() {
            let mut acc = rc[j];
            for (m, s) in self.mds[j].iter().zip(sbox.iter()) {
                acc = acc + *m * *s;
            }
            *o = acc;
        }
        out
    }

    /// The round constant for round `r`, exposed so the membership AIR can build
    /// its periodic columns from the same schedule the hash uses.
    pub fn round_constant(&self, r: usize) -> [Fp; WIDTH] {
        self.rc[r]
    }

    /// The full permutation: every round applied to a state. This is the
    /// primitive a Poseidon Merkle commitment compresses with, and because it is
    /// all field operations it can be arithmetized, which is what makes a
    /// commitment recursion-friendly.
    pub fn permute(&self, mut state: [Fp; WIDTH]) -> [Fp; WIDTH] {
        let rounds = 1usize << self.log_t;
        for r in 0..rounds {
            state = self.round(&state, r);
        }
        state
    }

    /// A fixed-length two-to-one compression: place two rate-sized digests in the
    /// full state, permute, and return the first rate lanes. This is the node
    /// hash of a Poseidon Merkle tree.
    pub fn compress(&self, left: &[Fp; RATE], right: &[Fp; RATE]) -> [Fp; RATE] {
        let mut state = [Fp::ZERO; WIDTH];
        state[..RATE].copy_from_slice(left);
        state[RATE..].copy_from_slice(right);
        let out = self.permute(state);
        let mut digest = [Fp::ZERO; RATE];
        digest.copy_from_slice(&out[..RATE]);
        digest
    }

    /// A fixed-arity field commitment: a compress-tree over eleven field elements
    /// padded to sixteen with a domain tag, built only from the two-to-one
    /// compression. The input length is fixed, so there is no padding ambiguity and
    /// collision resistance reduces to that of `compress`. Layout: the eleven
    /// elements, then `NOTE_DOMAIN`, then four zeros; compress the four rate-sized
    /// quarters into two digests, then compress those into the commitment.
    pub fn commit_note(&self, limbs: &[Fp; NOTE_LIMBS]) -> [Fp; RATE] {
        let mut p = [Fp::ZERO; 16];
        p[..NOTE_LIMBS].copy_from_slice(limbs);
        p[NOTE_LIMBS] = Fp::from_u64(NOTE_DOMAIN);
        // p[12..16] stay zero.
        let q0 = [p[0], p[1], p[2], p[3]];
        let q1 = [p[4], p[5], p[6], p[7]];
        let q2 = [p[8], p[9], p[10], p[11]];
        let q3 = [p[12], p[13], p[14], p[15]];
        let d0 = self.compress(&q0, &q1);
        let d1 = self.compress(&q2, &q3);
        self.compress(&d0, &d1)
    }

    /// One round over any field: a full x^7 S-box layer, the MDS mix, then the
    /// round constants. The MDS entries are base-field constants, embedded through
    /// `from_base`. Shared by the hash constraint and the Merkle-path constraint so
    /// both are proven at money-grade soundness from one implementation.
    pub fn round_generic<F: Felt>(&self, state: &[F; WIDTH], rc: &[F; WIDTH]) -> [F; WIDTH] {
        let mut sbox = [F::ZERO; WIDTH];
        for (s, v) in sbox.iter_mut().zip(state.iter()) {
            *s = v.pow(7);
        }
        let mut out = [F::ZERO; WIDTH];
        for (j, o) in out.iter_mut().enumerate() {
            let mut acc = rc[j];
            for (m, s) in self.mds[j].iter().zip(sbox.iter()) {
                acc = acc + F::from_base(*m) * *s;
            }
            *o = acc;
        }
        out
    }

    /// The hash transition constraint over any field: the next state is one round
    /// of the current state under this row's constants. `window = [state, next]`,
    /// `periodic` = the round-constant lanes.
    fn transition_impl<F: Felt>(&self, window: &[F], periodic: &[F]) -> Vec<F> {
        let mut state = [F::ZERO; WIDTH];
        state.copy_from_slice(&window[..WIDTH]);
        let mut rc = [F::ZERO; WIDTH];
        rc.copy_from_slice(&periodic[..WIDTH]);
        let pr = self.round_generic(&state, &rc);
        let mut out = Vec::with_capacity(WIDTH);
        for (j, o) in pr.iter().enumerate() {
            out.push(window[WIDTH + j] - *o);
        }
        out
    }
}

impl AirExt for Poseidon {
    fn transition_ext(&self, window: &[Fp2], periodic: &[Fp2]) -> Vec<Fp2> {
        self.transition_impl(window, periodic)
    }
}

impl Air for Poseidon {
    fn log_trace_len(&self) -> u32 {
        self.log_t
    }

    fn trace_width(&self) -> usize {
        WIDTH
    }

    fn window_size(&self) -> usize {
        2
    }

    fn constraint_degree(&self) -> usize {
        7
    }

    fn num_transition(&self) -> usize {
        WIDTH
    }

    fn periodic_columns(&self) -> Vec<Vec<Fp>> {
        // One column per lane: the round constant for that lane at each round.
        (0..WIDTH).map(|j| self.rc.iter().map(|row| row[j]).collect()).collect()
    }

    fn transition(&self, window: &[Fp], periodic: &[Fp]) -> Vec<Fp> {
        self.transition_impl(window, periodic)
    }

    fn boundary(&self) -> Vec<(usize, usize, Fp)> {
        let last = (1usize << self.log_t) - 1;
        let mut b = Vec::with_capacity(WIDTH);
        // Capacity lanes initialized to zero: the sponge domain separation.
        for j in RATE..WIDTH {
            b.push((j, 0, Fp::ZERO));
        }
        // Final rate lanes are the public digest.
        for (j, d) in self.digest.iter().enumerate() {
            b.push((j, last, *d));
        }
        b
    }
}

/// A Cauchy matrix `M[i][j] = 1 / (x_i - y_j)` with disjoint node sets
/// `x_i = i` and `y_j = WIDTH + j`. Cauchy matrices are MDS for any distinct
/// nodes, so this is a real diffusion layer.
fn cauchy_mds() -> [[Fp; WIDTH]; WIDTH] {
    let mut m = [[Fp::ZERO; WIDTH]; WIDTH];
    for (i, row) in m.iter_mut().enumerate() {
        for (j, cell) in row.iter_mut().enumerate() {
            let x = Fp::from_u64(i as u64);
            let y = Fp::from_u64((WIDTH + j) as u64);
            *cell = (x - y).inv();
        }
    }
    m
}

/// Nothing-up-my-sleeve round constants: the BLAKE3 hash of a domain string with
/// the round and lane indices, reduced into the field.
fn round_constants(rounds: usize) -> Vec<[Fp; WIDTH]> {
    let mut rc = Vec::with_capacity(rounds);
    for r in 0..rounds {
        let mut row = [Fp::ZERO; WIDTH];
        for (j, cell) in row.iter_mut().enumerate() {
            let mut buf = Vec::with_capacity(RC_DOMAIN.len() + 16);
            buf.extend_from_slice(RC_DOMAIN);
            buf.extend_from_slice(&(r as u64).to_le_bytes());
            buf.extend_from_slice(&(j as u64).to_le_bytes());
            let h = blake3_hash(&buf);
            let v = u64::from_le_bytes([h[0], h[1], h[2], h[3], h[4], h[5], h[6], h[7]]);
            *cell = Fp::from_u64(v);
        }
        rc.push(row);
    }
    rc
}
