// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Lagrange evaluation of the low-degree extension. Given a set of points, this
//! evaluates the unique interpolating polynomial of degree below the point count
//! at an arbitrary location, without materializing its coefficients. This is the
//! operation a STARK uses to move between a trace and its extension.

use super::super::field::{Fp, Fp2};
use alloc::vec::Vec;

/// Evaluate the polynomial that interpolates `(xs[i], ys[i])` at `z`. The `xs`
/// must be distinct; a repeated node makes the interpolant undefined and the
/// corresponding denominator zero, so callers pass distinct evaluation points.
pub fn eval_lagrange(xs: &[Fp], ys: &[Fp], z: Fp) -> Fp {
    let n = core::cmp::min(xs.len(), ys.len());
    let mut acc = Fp::ZERO;
    for i in 0..n {
        let mut num = Fp::ONE;
        let mut den = Fp::ONE;
        for j in 0..n {
            if i != j {
                num = num * (z - xs[j]);
                den = den * (xs[i] - xs[j]);
            }
        }
        acc = acc + ys[i] * num * den.inv();
    }
    acc
}

/// Evaluate the same interpolant at an extension point `z in Fp2`. The nodes and
/// values stay in the base field (a periodic column is public and base-valued);
/// only the evaluation point is in the extension, as the out-of-domain sampling of
/// a money-grade STARK requires. Agrees with `eval_lagrange` on a base-embedded z.
pub fn eval_lagrange_ext(xs: &[Fp], ys: &[Fp], z: Fp2) -> Fp2 {
    let n = core::cmp::min(xs.len(), ys.len());
    let mut acc = Fp2::ZERO;
    for i in 0..n {
        let mut num = Fp2::ONE;
        let mut den = Fp::ONE;
        for j in 0..n {
            if i != j {
                num = num * (z - Fp2::from_base(xs[j]));
                den = den * (xs[i] - xs[j]);
            }
        }
        acc = acc + Fp2::from_base(ys[i]) * num * Fp2::from_base(den.inv());
    }
    acc
}

/// Every column interpolated at `z` over the order-`t` subgroup generated by
/// `g`, in one pass. On that domain the Lagrange basis has the closed form
/// l_i(z) = (z^t - 1) * g^i / (t * (z - g^i)), so the denominators batch into
/// a single field inversion and the weights are shared by every column. The
/// generic quadratic form above walks t^2 products per column, which at a
/// deep trace domain is days; this is the same unique interpolant, so the
/// value cannot differ.
pub fn eval_cols_on_subgroup(g: Fp, t: usize, cols: &[Vec<Fp>], z: Fp) -> Vec<Fp> {
    let mut dens = Vec::with_capacity(t);
    let mut x = Fp::ONE;
    for _ in 0..t {
        dens.push(z - x);
        x = x * g;
    }
    let invs = super::inv::batch_inv(&dens);
    let scale = (z.pow(t as u64) - Fp::ONE) * Fp::from_u64(t as u64).inv();
    let mut weights = Vec::with_capacity(t);
    let mut gi = Fp::ONE;
    for iv in &invs {
        weights.push(scale * gi * *iv);
        gi = gi * g;
    }
    cols.iter()
        .map(|col| {
            let mut acc = Fp::ZERO;
            for (y, w) in col.iter().zip(&weights) {
                acc = acc + *y * *w;
            }
            acc
        })
        .collect()
}

/// Each column's polynomial at `z`, read from its coefficients rather than its
/// values on the subgroup.
///
/// Same polynomial and therefore the same value as
/// [`eval_cols_on_subgroup_ext`], which a test holds it to. It exists because a
/// caller that already has the coefficients can use this and drop the columns,
/// and on a wide outer the columns are gigabytes that would otherwise have to
/// stay alive until the out-of-domain point is drawn.
pub fn eval_coeff_cols_at_ext(coeffs: &[Vec<Fp>], z: Fp2) -> Vec<Fp2> {
    crate::par::map_slice(coeffs, |col| {
        let mut acc = Fp2::ZERO;
        for c in col.iter().rev() {
            acc = acc * z + Fp2::from_base(*c);
        }
        acc
    })
}

pub fn eval_cols_on_subgroup_ext(g: Fp, t: usize, cols: &[Vec<Fp>], z: Fp2) -> Vec<Fp2> {
    use super::inv::batch_inv;
    let mut dens = Vec::with_capacity(t);
    let mut x = Fp::ONE;
    for _ in 0..t {
        dens.push(z - Fp2::from_base(x));
        x = x * g;
    }
    let invs = batch_inv(&dens);
    // weight_i = (z^t - 1)/t * g^i / (z - g^i)
    let scale = (z.pow(t as u64) - Fp2::ONE) * Fp2::from_base(Fp::from_u64(t as u64).inv());
    let mut weights = Vec::with_capacity(t);
    let mut gi = Fp::ONE;
    for inv in &invs {
        weights.push(scale * Fp2::from_base(gi) * *inv);
        gi = gi * g;
    }
    /*
     * The weights are shared and each column's sum is independent, so the
     * columns divide across cores. On a wide outer this is 2,649 columns of a
     * quarter million rows each, which is the difference between one core
     * walking 694 million multiply-adds and the machine doing it. The sum
     * within a column stays in order, so every value is the one the serial
     * walk produced.
     */
    crate::par::map_slice(cols, |col| {
        let mut acc = Fp2::ZERO;
        for (y, w) in col.iter().zip(&weights) {
            acc = acc + Fp2::from_base(*y) * *w;
        }
        acc
    })
}

#[cfg(test)]
mod coeff_eval_tests {
    use super::*;
    use crate::poly::ntt::intt;
    use crate::fri::root_of_unity;

    /*
     * The coefficient evaluator against the barycentric one. They are the same
     * polynomial at the same point, so they must agree exactly; the prover
     * swapped to the first because it can drop the columns, and this is what
     * says the swap moved no value. A disagreement here changes what the
     * transcript absorbs and therefore every challenge after it.
     */
    #[test]
    fn evaluating_from_coefficients_matches_the_subgroup_form() {
        for log_t in [3u32, 6, 8] {
            let t = 1usize << log_t;
            let g = root_of_unity(log_t);
            let cols: Vec<Vec<Fp>> = (0..5)
                .map(|c| {
                    (0..t).map(|i| Fp::from_u64((7 * i as u64 + 3) * (c as u64 + 1) + 11)).collect()
                })
                .collect();
            let coeffs: Vec<Vec<Fp>> = cols.iter().map(|col| intt(col, g)).collect();
            let z = Fp2 { c0: Fp::from_u64(0x1234_5678_9abc_def0), c1: Fp::from_u64(42) };
            let bary = eval_cols_on_subgroup_ext(g, t, &cols, z);
            let horner = eval_coeff_cols_at_ext(&coeffs, z);
            assert_eq!(bary, horner, "the two evaluators disagree at log_t {log_t}");
        }
    }
}
